services:
  - type: web
    name: images-csv-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_TITLE
        value: Images CSV API
      - key: API_VERSION
        value: 1.0.0
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: sqlite:////opt/render/project/src/data/api_data.db
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
